// V26 Phase C2.1 deliverable — benches/quant_latency.rs
//
// Per-algorithm latency benchmarks for FajarQuant vs KIVI vs TurboQuant
// at 2/3/4 bit widths. Measures the time to quantize one (seq_len, d_head)
// shaped tensor that approximates a single Gemma 4 E2B KV cache layer.
//
// Per bench/METHODOLOGY.md §8.1 + §2 sample protocol:
//   - 100 samples per measurement
//   - 3 sec warmup (cache + HWP frequency stabilization)
//   - 10 sec measurement
//   - 95% confidence interval reported
//   - median (NOT mean) for outlier robustness
//
// Per bench/METHODOLOGY.md §3 — MUST be run after `bash bench/setup_perf.sh`
// to flip governor → performance, disable turbo, take HT siblings offline,
// and pin to even cores. Without setup_perf.sh, the noise floor is
// 0.720 ns (per bench/results/noise_floor.json) which corrupts sub-µs
// measurements. FajarQuant's per-layer quantize is O(microseconds) so
// the noise floor only matters if you're claiming sub-1.5 ns improvements
// (which we are not — typical deltas are 5-20% on µs-scale operations).
//
// How to use:
//   # First, apply paper-grade machine state (requires sudo):
//   bash bench/setup_perf.sh
//   # Then run:
//   cargo bench --bench quant_latency
//   # Restore default after:
//   bash bench/setup_perf.sh --restore
//
// Output:
//   target/criterion/quant_latency/<algorithm>_<bits>bit/
//     ├── estimates.json    (median + CI half-width)
//     ├── sample.json       (raw timing samples)
//     └── report/index.html (criterion's HTML report)
//
// V26 §C2.1 task table also calls for `bench/results/quant_latency.csv`.
// That CSV is generated by a separate post-process script (TBD as part of
// C2.1 substantive work) that walks target/criterion/quant_latency/*/
// and aggregates the estimates.json into one CSV row per (algorithm, bits).
// This file scaffolds the bench harness; the CSV aggregator is C2.1.x.

use criterion::{BenchmarkId, Criterion, criterion_group, criterion_main};
use ndarray::{Array1, Array2, Axis};
use ndarray_rand::RandomExt;
use ndarray_rand::rand_distr::Normal;

use fajarquant::adaptive::{
    CalibrationBuffer, adaptive_codebook, compute_pca_rotation, encode_adaptive,
};
use fajarquant::kivi::{kivi_quantize_keys, kivi_quantize_values};
use fajarquant::turboquant::{TurboQuantConfig, create_config, quant_mse};

// Test layer dimensions chosen to match Gemma 4 E2B (d_head=256) and
// Mistral 7B (d_head=128) — two of the V26 Phase C1 target models.
// seq_len 128 is short enough to bench in <1s per sample but long
// enough to amortize per-call overhead.
const SEQ_LEN: usize = 128;
const D_HEAD: usize = 128;
const BITS_TO_BENCH: [u8; 3] = [2, 3, 4];

/// Build a synthetic (SEQ_LEN, D_HEAD) tensor of N(0,1) samples.
/// The numerical accuracy of quantization depends on data distribution,
/// but LATENCY does not — it's dominated by per-element arithmetic
/// and memory traffic, both of which are constant for a given shape.
fn synthetic_layer() -> Array2<f64> {
    Array2::random((SEQ_LEN, D_HEAD), Normal::new(0.0, 1.0).unwrap())
}

/// KIVI per-channel key quantization at given bit width.
fn bench_kivi(c: &mut Criterion) {
    let data = synthetic_layer();
    let mut group = c.benchmark_group("kivi_quantize_keys");
    group.sample_size(100);
    group.warm_up_time(std::time::Duration::from_secs(3));
    group.measurement_time(std::time::Duration::from_secs(10));
    group.confidence_level(0.95);
    for bits in BITS_TO_BENCH {
        group.bench_with_input(BenchmarkId::from_parameter(bits), &bits, |b, &b_| {
            b.iter(|| kivi_quantize_keys(&data, b_));
        });
    }
    group.finish();
}

/// KIVI per-token value quantization at given bit width.
fn bench_kivi_values(c: &mut Criterion) {
    let data = synthetic_layer();
    let mut group = c.benchmark_group("kivi_quantize_values");
    group.sample_size(100);
    group.warm_up_time(std::time::Duration::from_secs(3));
    group.measurement_time(std::time::Duration::from_secs(10));
    group.confidence_level(0.95);
    for bits in BITS_TO_BENCH {
        group.bench_with_input(BenchmarkId::from_parameter(bits), &bits, |b, &b_| {
            b.iter(|| kivi_quantize_values(&data, b_));
        });
    }
    group.finish();
}

/// TurboQuant random-orthogonal-rotation + Lloyd-Max codebook quantization.
/// Config (rotation matrix, codebook) is built ONCE outside the iter loop —
/// only the per-vector quant is measured, matching how it would be used in
/// a real inference loop where codebooks are cached across many vectors.
fn bench_turboquant(c: &mut Criterion) {
    let data = synthetic_layer();
    let mut group = c.benchmark_group("turboquant_quant_mse");
    group.sample_size(100);
    group.warm_up_time(std::time::Duration::from_secs(3));
    group.measurement_time(std::time::Duration::from_secs(10));
    group.confidence_level(0.95);
    for bits in BITS_TO_BENCH {
        let config: TurboQuantConfig = create_config(D_HEAD, bits);
        group.bench_with_input(BenchmarkId::from_parameter(bits), &bits, |b, _| {
            b.iter(|| {
                // Quantize each row of the (SEQ_LEN, D_HEAD) matrix
                // independently — matches the per-token semantics of the
                // run_comparison.py reference implementation.
                let mut total_indices: usize = 0;
                for row in data.axis_iter(Axis(0)) {
                    let v: Array1<f64> = row.to_owned();
                    let qv = quant_mse(&v, &config);
                    total_indices = total_indices.wrapping_add(qv.indices.len());
                }
                criterion::black_box(total_indices)
            });
        });
    }
    group.finish();
}

/// FajarQuant adaptive PCA-rotation quantization. PCA rotation matrix +
/// data-specific Lloyd-Max codebook are built ONCE outside the iter loop —
/// only the per-row encode_adaptive call is measured. This matches the
/// deployment pattern where calibration happens at model load time and
/// per-token encodes happen in the hot path.
fn bench_fajarquant_adaptive(c: &mut Criterion) {
    let data = synthetic_layer();
    let mut group = c.benchmark_group("fajarquant_encode_adaptive");
    group.sample_size(100);
    group.warm_up_time(std::time::Duration::from_secs(3));
    group.measurement_time(std::time::Duration::from_secs(10));
    group.confidence_level(0.95);

    // Collect calibration vectors once for all bit widths.
    let mut calib = CalibrationBuffer::new(D_HEAD, SEQ_LEN);
    let mut calib_data: Vec<Array1<f64>> = Vec::with_capacity(SEQ_LEN);
    for row in data.axis_iter(Axis(0)) {
        let v: Array1<f64> = row.to_owned();
        calib_data.push(v.clone());
        calib.add(v);
    }
    let rotation: Array2<f64> = compute_pca_rotation(&calib);

    for bits in BITS_TO_BENCH {
        // Build the data-specific Lloyd-Max codebook for this bit width.
        let codebook = adaptive_codebook(&rotation, &calib_data, bits);

        group.bench_with_input(BenchmarkId::from_parameter(bits), &bits, |b, _| {
            b.iter(|| {
                let mut total_indices: usize = 0;
                for row in data.axis_iter(Axis(0)) {
                    let v: Array1<f64> = row.to_owned();
                    let encoded = encode_adaptive(&v, &rotation, &codebook);
                    total_indices = total_indices.wrapping_add(encoded.indices.len());
                }
                criterion::black_box(total_indices)
            });
        });
    }
    group.finish();
}

criterion_group!(
    benches,
    bench_kivi,
    bench_kivi_values,
    bench_turboquant,
    bench_fajarquant_adaptive,
);
criterion_main!(benches);
